M48
; DRILL file {KiCad 8.0.1} date 2024-06-09T20:13:58+0200
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-06-09T20:13:58+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1063
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1280
%
G90
G05
T1
X4.9551Y-3.3803
X4.9551Y-5.2701
X6.2543Y-3.3803
X6.2543Y-5.2701
T2
X4.0896Y-3.6992
X4.5396Y-3.6992
M30
